### ISSUE TITLE
a minor bug in the graph partition module.

### ISSUE THREAD

**Issue by wuyifan18** [yaobaiwei/GMiner#6]
Hi @yaobaiwei,  thanks for the great work.
I have read the source code of the graph partition module, however, I found a minor bug when calculating the priority to allocate blocks. This part of the code is as follows:
https://github.com/yaobaiwei/GMiner/blob/c09693f75747eb81cb9fd708187ca59c6633d10d/partition/BDGPartitioner.tpp#L189
Here, the integer type should be converted to a double type in the division operation.
I have fixed the bug and pull a [request](https://github.com/yaobaiwei/GMiner/pull/5).

**Comment by yaobaiwei** [comment]
> Hi @yaobaiwei, thanks for the great work.
> I have read the source code of the graph partition module, however, I found a minor bug when calculating the priority to allocate blocks. This part of the code is as follows:
> https://github.com/yaobaiwei/GMiner/blob/c09693f75747eb81cb9fd708187ca59c6633d10d/partition/BDGPartitioner.tpp#L189
> 
> 
> Here, the integer type should be converted to a double type in the division operation.
> I have fixed the bug and pull a [request](https://github.com/yaobaiwei/GMiner/pull/5).

Thanks a lot, Yifan!
